from django.urls import path
from . import merchant, operations, payment_views, views, recovery, counter
from .proxy import amap_proxy
from . import discovery_api

urlpatterns = [
    path('health', views.health),
    path('config', views.config), path('auth/me', views.me), path('auth/csrf', views.csrf_token),
    path('auth/login', views.login_view), path('auth/register', views.register), path('auth/logout', views.logout_view),
    path('auth/profile', views.profile), path('auth/password', views.password), path('auth/account', views.account),
    path('auth/recovery', recovery.manage_recovery), path('auth/recovery/reset', recovery.reset_password),
    path('products', discovery_api.products), path('stalls/map', discovery_api.map_stalls),
    path('stalls', views.stalls), path('stalls/<int:stall_id>', views.stall_detail),
    path('stalls/<int:stall_id>/follow', views.follow), path('follows', views.follows),
    path('events', views.event), path('feedback', operations.feedback),
    path('orders', views.orders), path('orders/active-summary', views.active_order_summary),
    path('orders/recent-completed', operations.recent_completed),
    path('orders/<uuid:order_id>', views.order_detail),
    path('orders/<uuid:order_id>/payments/wechat', payment_views.start),
    path('orders/<uuid:order_id>/payments/simulate', payment_views.simulate),
    path('orders/<uuid:order_id>/payments/sync', payment_views.sync),
    path('orders/<uuid:order_id>/payments/close', payment_views.close),
    path('payments/wechat/notify/<slug:account_key>', payment_views.notify),
    path('orders/<uuid:order_id>/cancel', views.cancel), path('orders/<uuid:order_id>/review', views.review),
    path('orders/<uuid:order_id>/confirm-receipt', views.receive_delivery),
    path('merchant/stalls', merchant.stalls), path('merchant/orders', views.merchant_orders),
    path('merchant/application', operations.application),
    path('merchant/application/submit', operations.submit_application),
    path('merchant/stalls/<int:stall_id>/restock', operations.restock),
    path('merchant/stalls/<int:stall_id>/location-reports', operations.location_reports),
    path('merchant/stalls/<int:stall_id>/status', views.merchant_status),
    path('merchant/stalls/<int:stall_id>/profile', merchant.profile),
    path('merchant/stalls/<int:stall_id>/delivery', merchant.delivery),
    path('merchant/stalls/<int:stall_id>/services', merchant.services),
    path('merchant/stalls/<int:stall_id>/products', merchant.products),
    path('merchant/stalls/<int:stall_id>/image', merchant.upload_image),
    path('merchant/products/<int:product_id>', merchant.product),
    path('merchant/products/<int:product_id>/stock-correction', counter.stock_correction),
    path('merchant/stalls/<int:stall_id>/receiving-heartbeat', counter.receiving_heartbeat),
    path('merchant/stalls/<int:stall_id>/pickup-lookup', counter.pickup_lookup),
    path('merchant/reviews', merchant.reviews), path('merchant/reviews/<int:review_id>/reply', merchant.reply),
    path('merchant/orders/<uuid:order_id>/action', views.merchant_order_action), path('merchant/metrics', merchant.metrics),
    path('merchant/orders/<uuid:order_id>/refund', payment_views.refund),
    path('merchant/orders/<uuid:order_id>/refunds/simulate', payment_views.simulate_refund),
    path('amap-proxy/_AMapService/<path:upstream_path>', amap_proxy),
]
