# Generated by Django 5.2.17 on 2026-09-26 08:50

import django.db.models.deletion
import django.utils.timezone
import market.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="名称")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=160, verbose_name="描述"),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("is_demo", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "校园区域",
                "verbose_name_plural": "校园区域",
            },
        ),
        migrations.CreateModel(
            name="BusinessSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "出摊中"),
                            ("paused", "暂歇"),
                            ("closed", "已收摊"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_confirmed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "营业会话",
                "verbose_name_plural": "营业会话",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="商品名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="商品描述"
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="图片地址"
                    ),
                ),
                ("price_cents", models.PositiveIntegerField(verbose_name="价格（分）")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="库存")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stale_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="位置过期分钟数"
                    ),
                ),
                (
                    "pending_minutes",
                    models.PositiveIntegerField(
                        default=5, verbose_name="接单超时分钟数"
                    ),
                ),
            ],
            options={
                "verbose_name": "运营参数",
                "verbose_name_plural": "运营参数",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("target", models.CharField(max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "业务审计日志",
                "verbose_name_plural": "业务审计日志",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "意见反馈",
                "verbose_name_plural": "意见反馈",
            },
        ),
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=120, verbose_name="经营主体"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="公开联系电话"
                    ),
                ),
                (
                    "qualification_note",
                    models.TextField(blank=True, verbose_name="经营资质公示"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="资质已核验"),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="许可证号"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "商户档案",
                "verbose_name_plural": "商户档案",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default=market.models.order_number, max_length=40, unique=True
                    ),
                ),
                ("stall_name", models.CharField(max_length=80)),
                ("stall_image", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待接单"),
                            ("preparing", "制作中"),
                            ("ready", "待取餐"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("rejected", "已拒单"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "未收款"), ("paid", "已收款")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("total_cents", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "pickup_code",
                    models.CharField(default=market.models.pickup_code, max_length=8),
                ),
                ("pickup_address", models.CharField(max_length=200)),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("cancel_reason", models.CharField(blank=True, max_length=200)),
                ("inventory_released", models.BooleanField(default=False)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("image", models.CharField(blank=True, max_length=500)),
                ("unit_price_cents", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="market.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="摊位名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("category", models.CharField(max_length=30, verbose_name="品类")),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="图片地址"
                    ),
                ),
                (
                    "prep_minutes",
                    models.PositiveIntegerField(
                        default=10, verbose_name="预计备餐分钟"
                    ),
                ),
                (
                    "transaction_enabled",
                    models.BooleanField(default=False, verbose_name="允许在线接单"),
                ),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="对用户显示"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stalls",
                        to="market.area",
                    ),
                ),
                (
                    "current_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="market.businesssession",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stalls",
                        to="market.merchantprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "摊位",
                "verbose_name_plural": "摊位",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="stall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="market.stall",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="market.stall",
            ),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.stall"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(db_index=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.stall",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="businesssession",
            name="stall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="market.stall",
            ),
        ),
        migrations.CreateModel(
            name="StallLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="取餐位置")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stall",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="market.stall",
                    ),
                ),
            ],
            options={
                "verbose_name": "摊位位置",
                "verbose_name_plural": "摊位位置",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="market.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="market.stall",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价",
                "verbose_name_plural": "评价",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="review_valid_rating",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_cents__gte", 1)),
                name="product_positive_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="unique_order_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_cents__gte", 1)),
                name="order_positive_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "stall"), name="unique_follow"
            ),
        ),
    ]
