# Generated by Django 5.2.17 on 2026-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_postgis_spatial_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, default="招牌美味", max_length=30, verbose_name="菜单分类"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="merchant_reply",
            field=models.CharField(blank=True, max_length=500, verbose_name="商家回复"),
        ),
        migrations.AddField(
            model_name="review",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="回复时间"),
        ),
    ]
