# Generated by Django 5.2.17 on 2026-09-26 12:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_product_category_review_merchant_reply_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="wechat_pay_account",
            field=models.CharField(
                blank=True,
                help_text="仅绑定该经营主体自有商户号；密钥由部署配置管理。",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="独立微信收款配置标识",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("offline", "到摊付款"), ("wechat", "微信支付")],
                default="offline",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_review_required",
            field=models.BooleanField(default=False, verbose_name="支付异常待核对"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "未收款"),
                    ("paid", "已收款"),
                    ("refunding", "退款中"),
                    ("refunded", "已退款"),
                ],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_key", models.CharField(max_length=64)),
                ("mchid", models.CharField(max_length=32)),
                ("appid", models.CharField(max_length=32)),
                ("out_trade_no", models.CharField(max_length=32, unique=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("native", "微信扫码"), ("h5", "手机微信支付")],
                        max_length=10,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="CNY", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "正在创建"),
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("closed", "已关闭"),
                            ("reconcile", "结果待确认"),
                            ("review", "需人工核对"),
                        ],
                        db_index=True,
                        default="creating",
                        max_length=12,
                    ),
                ),
                ("code_url", models.CharField(blank=True, max_length=4096)),
                ("h5_url", models.CharField(blank=True, max_length=4096)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=200)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="market.merchantprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="market.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "微信支付记录",
                "verbose_name_plural": "微信支付记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("out_refund_no", models.CharField(max_length=64, unique=True)),
                (
                    "refund_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "正在申请"),
                            ("processing", "退款处理中"),
                            ("success", "已退款"),
                            ("closed", "退款关闭"),
                            ("abnormal", "退款异常"),
                            ("reconcile", "结果待确认"),
                        ],
                        db_index=True,
                        default="creating",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_refund",
                        to="market.order",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund",
                        to="market.paymentattempt",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "微信退款记录",
                "verbose_name_plural": "微信退款记录",
            },
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_cents__gte", 1)),
                name="payment_positive_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["creating", "pending", "reconcile", "review"])
                ),
                fields=("order",),
                name="one_active_payment_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_cents__gte", 1)),
                name="refund_positive_amount",
            ),
        ),
    ]
