# Generated by Django 5.2.17 on 2026-09-27 02:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_merchantprofile_wechat_pay_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_eta_max_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_eta_min_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_fee_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_issue",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_point_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_point_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_point_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_point_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_type",
            field=models.CharField(
                choices=[("pickup", "到摊自取"), ("delivery", "商家配送")],
                default="pickup",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="request_in_flight_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_approved",
            field=models.BooleanField(default=False, verbose_name="运营配送准入通过"),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_capacity",
            field=models.PositiveIntegerField(
                default=5, verbose_name="同时进行配送订单上限"
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_enabled",
            field=models.BooleanField(default=False, verbose_name="商家开启配送"),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_ends_at",
            field=models.TimeField(
                default=datetime.time(14, 0), verbose_name="配送结束时间"
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_eta_max_minutes",
            field=models.PositiveIntegerField(
                default=45, verbose_name="预计送达上限分钟"
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_eta_min_minutes",
            field=models.PositiveIntegerField(
                default=25, verbose_name="预计送达下限分钟"
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_fee_cents",
            field=models.PositiveIntegerField(default=300, verbose_name="配送费（分）"),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_min_order_cents",
            field=models.PositiveIntegerField(
                default=1500, verbose_name="起送餐费（分）"
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_starts_at",
            field=models.TimeField(
                default=datetime.time(11, 0), verbose_name="配送开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "待付款"),
                    ("pending", "待接单"),
                    ("preparing", "制作中"),
                    ("ready", "待取餐"),
                    ("delivering", "配送中"),
                    ("arrived", "已到交接点"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("rejected", "已拒单"),
                ],
                db_index=True,
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrefund",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="交接点名称")),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="交接位置说明"),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="已获准开放交接"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_points",
                        to="market.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "配送交接点",
                "verbose_name_plural": "配送交接点",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="market.deliverypoint",
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="delivery_points",
            field=models.ManyToManyField(
                blank=True, related_name="stalls", to="market.deliverypoint"
            ),
        ),
    ]
