# Generated by Django 5.2.17 on 2026-09-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_order_arrived_at_order_delivery_eta_max_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="request_in_flight_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
