# Generated by Django 5.2.17 on 2026-09-27 03:14

from django.db import migrations, models


def mark_legacy_demo_orders(apps, schema_editor):
    # Existing demo cash exercises have never involved a gateway. Preserve that
    # provenance in reports; never reclassify any existing gateway transaction.
    Order = apps.get_model('market', 'Order')
    Order.objects.filter(stall__is_demo=True, payments__isnull=True).update(mode='simulation')


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_paymentattempt_request_in_flight_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypoint",
            name="is_simulation",
            field=models.BooleanField(default=False, verbose_name="仅模拟交接点"),
        ),
        migrations.AddField(
            model_name="order",
            name="mode",
            field=models.CharField(
                choices=[("live", "正式"), ("simulation", "模拟")],
                default="live",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="mode",
            field=models.CharField(
                choices=[("live", "正式"), ("simulation", "模拟")],
                default="live",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="simulation_settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="simulation_state",
            field=models.CharField(default="NOTPAY", max_length=16),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="mode",
            field=models.CharField(
                choices=[("live", "正式"), ("simulation", "模拟")],
                default="live",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="simulation_settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="simulation_state",
            field=models.CharField(default="SUCCESS", max_length=16),
        ),
        migrations.AddField(
            model_name="stall",
            name="simulation_defaults_prepared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stall",
            name="simulation_delivery_enabled",
            field=models.BooleanField(default=False, verbose_name="模拟外卖"),
        ),
        migrations.AddField(
            model_name="stall",
            name="simulation_payment_enabled",
            field=models.BooleanField(default=False, verbose_name="模拟线上支付"),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="channel",
            field=models.CharField(
                choices=[
                    ("native", "微信扫码"),
                    ("h5", "手机微信支付"),
                    ("simulation", "模拟支付"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(mark_legacy_demo_orders, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='deliverypoint',
            constraint=models.UniqueConstraint(fields=['area'], condition=models.Q(is_simulation=True), name='one_simulation_point_per_area'),
        ),
    ]
