# Generated by Django 5.2.17 on 2026-09-29 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_deliverypoint_is_simulation_order_mode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="kind",
            field=models.CharField(
                choices=[
                    ("general", "意见建议"),
                    ("not_found", "没找到摊位"),
                    ("wrong_location", "位置不对"),
                    ("mismatch", "信息不符"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="location_snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="用户看到的位置记录（未经核实）"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="request_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="feedback",
            name="stall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_reports",
                to="market.stall",
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="accepting_orders",
            field=models.BooleanField(default=True, verbose_name="接收新订单"),
        ),
        migrations.AddField(
            model_name="stall",
            name="arrival_image",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="认摊现场照片"
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="arrival_note",
            field=models.CharField(blank=True, max_length=200, verbose_name="认摊说明"),
        ),
        migrations.AddField(
            model_name="stall",
            name="location_draft_address",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="待核验位置草稿"
            ),
        ),
        migrations.CreateModel(
            name="MerchantApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("self", "自主填写"), ("assisted", "运营代录")],
                        default="self",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "待审核"),
                            ("needs_changes", "待补充"),
                            ("approved", "已批准建档"),
                            ("rejected", "未通过"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="经营主体"
                    ),
                ),
                (
                    "stall_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="摊位名称"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="联系电话"
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=30, verbose_name="品类"),
                ),
                (
                    "address_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="位置说明（待核验）"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="经营介绍"
                    ),
                ),
                (
                    "review_note",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="审核意见"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="本人确认资料时间"
                    ),
                ),
                (
                    "approved_stall",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="market.stall",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="market.area",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchant_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "商家入驻申请",
                "verbose_name_plural": "商家入驻申请",
            },
        ),
        migrations.CreateModel(
            name="RestockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restock_batches",
                        to="market.stall",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stall", "idempotency_key"),
                        name="unique_stall_restock_key",
                    )
                ],
            },
        ),
    ]
