# Generated by Django 5.2.17 on 2026-09-29 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_merchant_onboarding_and_visit_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="estimated_ready_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="商家预计出餐时间"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prep_delay_reason",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="备餐调整说明"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prep_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="备餐预估确认时间"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="portions",
            field=models.JSONField(
                blank=True, default=list, verbose_name="每份口味与备注快照"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="taste_options",
            field=models.JSONField(
                blank=True, default=list, verbose_name="免费口味选项"
            ),
        ),
        migrations.CreateModel(
            name="PreparationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparation_requests",
                        to="market.order",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "idempotency_key"),
                        name="unique_preparation_request",
                    )
                ],
            },
        ),
    ]
