# Generated by Django 5.2.17 on 2026-09-29 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_tastes_and_preparation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stall",
            name="usual_hours",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="通常出摊时段（计划）"
            ),
        ),
        migrations.CreateModel(
            name="AccountRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(blank=True, max_length=64)),
                ("password_stamp", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_recovery",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "账号恢复码状态",
                "verbose_name_plural": "账号恢复码状态",
            },
        ),
    ]
