# Generated by Django 5.2.17 on 2026-09-29 22:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0010_account_recovery_and_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("stock_before", models.PositiveIntegerField()),
                ("stock_after", models.PositiveIntegerField()),
                ("version_before", models.PositiveBigIntegerField()),
                ("version_after", models.PositiveBigIntegerField()),
                (
                    "reason",
                    models.CharField(max_length=200, verbose_name="盘点更正原因"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "线上可售余量更正记录",
                "verbose_name_plural": "线上可售余量更正记录",
            },
        ),
        migrations.AddField(
            model_name="businesssession",
            name="stop_orders_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="本场停止线上接单时间"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="help_reports",
                to="market.order",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_paused",
            field=models.BooleanField(default=False, verbose_name="暂停供应"),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_version",
            field=models.PositiveBigIntegerField(
                default=0, editable=False, verbose_name="库存版本"
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="prep_capacity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="同时备餐订单上限",
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="receiving_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="接单页最近成功同步"
            ),
        ),
        migrations.AddConstraint(
            model_name="stall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("prep_capacity__isnull", True),
                    models.Q(("prep_capacity__gte", 1), ("prep_capacity__lte", 100)),
                    _connector="OR",
                ),
                name="valid_prep_capacity",
            ),
        ),
        migrations.AddField(
            model_name="stockcorrection",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="stockcorrection",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_corrections",
                to="market.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcorrection",
            constraint=models.UniqueConstraint(
                fields=("product", "idempotency_key"),
                name="unique_stock_correction_key",
            ),
        ),
    ]
