# Generated by Django 5.2.17 on 2026-10-04 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0019_feedback_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="food_preparation_address",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="实际加工制作地址"
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="license_valid_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="许可证有效期至"
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="licensed_business_address",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="证照载明经营场所"
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="qualification_tier",
            field=models.CharField(
                choices=[
                    ("mobile_vendor", "流动摊位（到摊付款自取）"),
                    ("storefront", "实体门店（可开通线上支付与配送）"),
                ],
                default="mobile_vendor",
                help_text="只有核验过实体门店且证照地址齐全的商户才开放平台线上支付和配送。",
                max_length=20,
                verbose_name="经营资质类型",
            ),
        ),
        migrations.AddField(
            model_name="stall",
            name="payment_qr_image",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="摊主自有收款码"
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("qualification_tier", "mobile_vendor"),
                    models.Q(
                        ("qualification_tier", "storefront"),
                        models.Q(("licensed_business_address", ""), _negated=True),
                        models.Q(("food_preparation_address", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="storefront_requires_addresses",
            ),
        ),
    ]
