# Generated by Django 5.2.17 on 2026-10-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0020_qualification_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantprofile",
            name="qualification_tier",
            field=models.CharField(
                choices=[("mobile_vendor", "流动摊位（找摊与信息展示）"), ("storefront", "实体门店（经核验可开通线上交易）")],
                default="mobile_vendor", max_length=20, verbose_name="经营资质类型",
                help_text="公开展示不等于交易准入；只有经营资格核验有效并获运营授权的实体门店才开放线上下单、支付与配送。",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="display_availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "沿用原供应状态"),
                    ("available", "今天有"),
                    ("sold_out", "卖完了"),
                    ("paused", "暂时不卖"),
                ],
                default="",
                max_length=12,
                verbose_name="找摊展示供应状态",
            ),
        ),
    ]
